name: circrna
channels:
  - conda-forge
  - bioconda
  - defaults
  - agbiome 
dependencies:
  - agbiome::bbtools
  - bioconda::fastqc=0.11.9
  - bioconda::multiqc=1.8
  - bioconda::circexplorer2=2.3.8
  - bioconda::mapsplice>=2.1.9
  - bioconda::BWA>=0.6.2-r126
  - bioconda::miranda
  - conda-forge::python=2.7.15
