name: circrna
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::fastqc=0.11.9
  - bioconda::multiqc=1.8
  - bioconda::bwa=0.7.17
  - bioconda::samtools=1.10
  - bioconda::circexplorer2=2.3.8
  - bioconda::mapsplice=2.2.1
  - bioconda::circminer=0.4.2
  - conda-forge::python=2.7.15
