name: circrna
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::fastqc=0.11.9
  - bioconda::multiqc=1.8
  - bioconda::bedtools==2.29.2
  - bioconda::bwa=0.7.17
  - bioconda::pysam=0.15.2
  - bioconda::argparse=1.2.1
  - bioconda::bedtools=2.29.2
  - bioconda::hisat2=2.2.1
  - bioconda::samtools=1.10
  - bioconda::circexplorer2=2.3.8
  - bioconda::mapsplice=2.2.1
  - bioconda::circminer=0.4.2
  - conda-forge::pyyaml=5.1.1
  - conda-forge::scikit-learn=0.20.3
  - conda-forge::scipy=1.2.2
  - conda-forge::python=2.7.15
  - conda-forge::numexpr=2.7.1
  - conda-forge::numpy=1.16.4
